### ISSUE TITLE
Manual Save Broken

### ISSUE THREAD

**Issue by PinkPenguin418** [liana-p/narrat-engine#235]
**Describe the bug**
When doing a manual save the game stops working. We receive the following error in the debugger "Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'layers')". Identified the potential culprit to be the variable "save.screen.layers[0]" in the "save-slot-ui.vue" file on line 77 and 78. It should likely be "save.screens.layers[0]"

**To Reproduce**
1. In code have a line that uses save "Manual Save 1"
2. Run that line.

**Expected behavior**
I'd expect the manual save dialog to appear.

**Screenshots**
No screenshots available

**Browser**
Running this on latest version of Chrome.

**Comment by PinkPenguin418** [comment]
Ok, explored a bit more (tried to fix it myself). Appears that sometimes save.screens.layers[0] is need other times its save.screen.layers[0].

**Comment by PinkPenguin418** [comment]
figured it out, it was old saves that were showing up as save.screen.layers[0] instead of save.screens.layers[0]. I removed them and now only see save.screens.layers[0]. I'll see if I can create a PR.

**Comment by liana-p** [comment]
fixed by #236

**Comment by liana-p** [comment]
I just made a release with the change, should be 3.9.8
