### ISSUE TITLE
[BUG] Error when attempting to create a project with Yarn on WSL

### ISSUE THREAD

**Issue by lewdum** [liana-p/narrat-engine#36]
**Describe the bug**
Hi. On Linux (or at least WSL 2), attempting to run `yarn create narrat` results in this error:

```/usr/bin/env: ‘node\r’: No such file or directory```

This is apparently because the `create-narrat` script has CRLF line endings. Changing them to just LF allows project creation to proceed as normal.

**To Reproduce**
1. Simply run `yarn create narrat` on WSL (and possibly other Linux environments)

**Screenshots**
![error message](https://user-images.githubusercontent.com/10253775/202267797-b44933e2-8530-4f17-83c3-00b0c2e39e0c.png)

Thanks!

**Comment by liana-p** [comment]
Thanks for letting me know. I don't have WSL installed on windows right now so I've only tested on Mac and Windows. Going to try reinstalling it to check it.

It probably has CRLF in it if I made a release from Windows... maybe just doing another release from my Mac would fix it. I don't really know if there's a way to stop Windows from using CRLF

I'm surprised it makes the script crash though, strange

**Comment by lewdum** [comment]
Thank you! I think git itself replaces line endings by CRLF, as I often get this message when committing:

```
warning: LF will be replaced by CRLF in _____
The file will have its original line endings in your working directory
```

You could ask git not to do the conversion, but I agree that yarn shouldn't be having this issue at all in the first place, so maybe it merits further investigation.

**Comment by liana-p** [comment]
> I think git itself replaces line endings by CRLF

Yes, it auto changes to LF before committing to avoid issues with Unix systems which is correct, what breaks is having the CRLF from Windows. But since I did the release from a Windows PC, it still had the windows line endings because the conversion would only happen for committing.

there's a [bug](https://github.com/yarnpkg/yarn/issues/5480) in yarn about this which seems to have never been fixed. npm apparently sneakily fixes line endings for you behind the scenes, while yarn doesn't.

Seems a solution is to just add config files for the IDE to save files with LF instead of the default CRLF, so I'll try to set that up.

**Comment by lewdum** [comment]
Oh, I see what you mean now. For what's worth, other than this issue, Yarn has been working great out of the box. I was able to install dependencies and start the development server 👍

**Comment by liana-p** [comment]
I've released a new version of create-narrat, seems like it fixes the issue with yarn. Also added more config files to make sure editors on windows use LF

**Comment by lewdum** [comment]
Awesome! Now it creates successfully and even shows the commands at the end with `yarn` instead of `npm`, which I think didn't happen before. I'll be closing the issue with this comment, hope that's okay. (Also editing the issue's text to give the image a more permanent URL because I goofed up.)

![Screenshot 2022-11-16 153313](https://user-images.githubusercontent.com/10253775/202265112-162f0e13-225d-4d0f-8ad7-46a710153a8b.png)
